p8105_hw2_xl3494
================

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(lubridate)
library(readxl)
```

# Problem 1

Clean the data in pols-month.csv:

``` r
pols_month =
  read_csv("./fivethirtyeight_datasets/pols-month.csv")|>
  separate(mon, into = c("year", "nmonth", "day"), sep = "-", convert = TRUE) |>
  mutate(
    month = factor(tolower(month.name[nmonth]),   #name months
                   levels = tolower(month.name),  
                   ordered = TRUE)) |>
  mutate(president = if_else(prez_gop == 1, "gop", "dem")) |>  #create var president
  arrange(year, month) |>
  select(year, month, everything(), -nmonth, -day, -prez_gop, -prez_dem)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
pols_month 
```

    ## # A tibble: 822 × 9
    ##     year month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <int> <ord>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1  1947 january        23      51     253      23      45     198 dem      
    ##  2  1947 february       23      51     253      23      45     198 dem      
    ##  3  1947 march          23      51     253      23      45     198 dem      
    ##  4  1947 april          23      51     253      23      45     198 dem      
    ##  5  1947 may            23      51     253      23      45     198 dem      
    ##  6  1947 june           23      51     253      23      45     198 dem      
    ##  7  1947 july           23      51     253      23      45     198 dem      
    ##  8  1947 august         23      51     253      23      45     198 dem      
    ##  9  1947 september      23      51     253      23      45     198 dem      
    ## 10  1947 october        23      51     253      23      45     198 dem      
    ## # ℹ 812 more rows

Clean the data in snp.csv:

``` r
snp =
  read_csv("./fivethirtyeight_datasets/snp.csv")|>
  separate(date, into = c("m", "d", "yy"), sep = "/", convert = TRUE) |>
  mutate(
    year  = if_else(yy >= 50, 1900L + yy, 2000L + yy),  # 50–99 → 1950–1999；00–49 → 2000–2049
    month = factor(tolower(month.name[m]),
                   levels = tolower(month.name), ordered = TRUE)) |>
  arrange(year, month) |>
  select(year, month, close)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp
```

    ## # A tibble: 787 × 3
    ##     year month     close
    ##    <int> <ord>     <dbl>
    ##  1  1950 january    17.0
    ##  2  1950 february   17.2
    ##  3  1950 march      17.3
    ##  4  1950 april      18.0
    ##  5  1950 may        18.8
    ##  6  1950 june       17.7
    ##  7  1950 july       17.8
    ##  8  1950 august     18.4
    ##  9  1950 september  19.5
    ## 10  1950 october    19.5
    ## # ℹ 777 more rows

Tidy the unemployment data:

``` r
unemployment =
  read_csv("./fivethirtyeight_datasets/unemployment.csv")|>
  janitor::clean_names() |>
  pivot_longer(
    cols = -year,
    names_to  = "ab_month",
    values_to = "unemployment") |>
  mutate(
    m_idx = match(ab_month, tolower(month.abb)),             
    month = factor(tolower(month.name[m_idx]),
                   levels = tolower(month.name), ordered = TRUE),
    year   = as.integer(year)) |>
  arrange(year, month) |>
  select(year, month, unemployment)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemployment
```

    ## # A tibble: 816 × 3
    ##     year month     unemployment
    ##    <int> <ord>            <dbl>
    ##  1  1948 january            3.4
    ##  2  1948 february           3.8
    ##  3  1948 march              4  
    ##  4  1948 april              3.9
    ##  5  1948 may                3.5
    ##  6  1948 june               3.6
    ##  7  1948 july               3.6
    ##  8  1948 august             3.9
    ##  9  1948 september          3.8
    ## 10  1948 october            3.7
    ## # ℹ 806 more rows

Joining snp into pols_month, then unemployment into result:

``` r
result_df = left_join(pols_month, snp, by = c("year","month"))
```

Joining unemployment into result:

``` r
pols_snp_unemp = left_join(result_df, unemployment, by = c("year","month"))

pols_snp_unemp
```

    ## # A tibble: 822 × 11
    ##     year month   gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##    <int> <ord>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <dbl>
    ##  1  1947 january      23      51     253      23      45     198 dem          NA
    ##  2  1947 februa…      23      51     253      23      45     198 dem          NA
    ##  3  1947 march        23      51     253      23      45     198 dem          NA
    ##  4  1947 april        23      51     253      23      45     198 dem          NA
    ##  5  1947 may          23      51     253      23      45     198 dem          NA
    ##  6  1947 june         23      51     253      23      45     198 dem          NA
    ##  7  1947 july         23      51     253      23      45     198 dem          NA
    ##  8  1947 august       23      51     253      23      45     198 dem          NA
    ##  9  1947 septem…      23      51     253      23      45     198 dem          NA
    ## 10  1947 october      23      51     253      23      45     198 dem          NA
    ## # ℹ 812 more rows
    ## # ℹ 1 more variable: unemployment <dbl>

### About the datasets

The pols-month table contains the monthly counts of politicians by party
– Republican/Democratic governors, senators, and representatives, and
the party of the sitting president. After cleaning, the time range is
from Jan 1947 to Jun 2015 (822 rows).

The snp table holds the Standard & Poor’s stock market index (close) by
year and month. After cleaning, it contains 787 rows with a time range
from Jan 1950 to Jul 2015.

The unemployment table records the monthly unemployment rate (%); we
pivoted it from wide (Jan–Dec columns) to long with the same keys – year
and month. The dataset contains 816 rows with a time range from Jan 1948
to Jun 2015.

The joined dataset pols_snp_unemp contains 822 rows and 11 variables.
Key variables include year, month, president, party counts (gov_gop,
sen_gop, rep_gop, gov_dem, sen_dem, and rep_dem), stock market index
(close), and % unemployment. The final table keeps all the pol-month
months from Jan 1947 to Jun 2015. The coverage of the other two dataset
differs slightly: snp_close covers from Jan 1950 to Jun 2015, and
unemployment covers from Jan 1948 to Jun 2015.

# Problem 2

Read in and clean the Mr. Trash Wheel sheet:

``` r
mr = 
  read_excel("./trashwheel_data/202509 Trash Wheel Collection Data.xlsx",
                           sheet = "Mr. Trash Wheel",
                           range = "A2:N709") |>
  janitor::clean_names()|>
  filter(!is.na(dumpster)) |>
  mutate(month = tolower(month),
         year  = as.integer(readr::parse_number(year)),
         date  = as.Date(date),
         sports_balls = as.integer(round(sports_balls)),
         wheel = "mr")
```

Read in and clean the Professor Trash Wheel sheet:

``` r
professor = 
  read_excel("./trashwheel_data/202509 Trash Wheel Collection Data.xlsx",
                           sheet = "Professor Trash Wheel",
                           range = "A2:M134") |>
  janitor::clean_names()|>
  filter(!is.na(dumpster)) |>
  mutate(month = tolower(month),
         date  = as.Date(date),
         wheel = "professor")
```

Read in and clean the Gwynns Falls Trash Wheel sheet:

``` r
gwynns = 
  read_excel("./trashwheel_data/202509 Trash Wheel Collection Data.xlsx",
                           sheet = "Gwynns Falls Trash Wheel",
                           range = "A2:L351") |>
  janitor::clean_names()|>
  filter(!is.na(dumpster)) |>
  mutate(month = tolower(month),
         date  = as.Date(date),
         wheel = "gwynns")
```

Bind all rows:

``` r
wheel_bind = 
  bind_rows(mr, professor, gwynns) |>
  select(wheel, dumpster, month, year, date, everything())

wheel_bind
```

    ## # A tibble: 1,188 × 15
    ##    wheel dumpster month  year date       weight_tons volume_cubic_yards
    ##    <chr>    <dbl> <chr> <dbl> <date>           <dbl>              <dbl>
    ##  1 mr           1 may    2014 2014-05-16        4.31                 18
    ##  2 mr           2 may    2014 2014-05-16        2.74                 13
    ##  3 mr           3 may    2014 2014-05-16        3.45                 15
    ##  4 mr           4 may    2014 2014-05-17        3.1                  15
    ##  5 mr           5 may    2014 2014-05-17        4.06                 18
    ##  6 mr           6 may    2014 2014-05-20        2.71                 13
    ##  7 mr           7 may    2014 2014-05-21        1.91                  8
    ##  8 mr           8 may    2014 2014-05-28        3.7                  16
    ##  9 mr           9 june   2014 2014-06-05        2.52                 14
    ## 10 mr          10 june   2014 2014-06-11        3.76                 18
    ## # ℹ 1,178 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>

### About the dataset

The combined Trash Wheel dataset contains 1188 observations and 15
variables spanning 2014–2025. Each row contains a dumpster with
identifiers `dumpster` and `wheel` (Mr., Professor, Gwynnda), timestamp
`date` (plus `year`, `month`), and material metrics such as
`weight_tons`, `volume_cubic_yards`, `plastic_bottles`, `polystyrene`,
`cigarette_butts`, `wrappers`, `sports_balls` (rounded to integers), and
`homes_powered`.

Professor Trash Wheel collected a total of 282.26 tons of trash.

In June 2022, Gwynnda collected 18,120 cigarette butts.

# Problem 3

read in and clean zillow_data

``` r
zori_data = 
  read_csv("./zillow_data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv") |>
  janitor::clean_names() |>
  select (
    region_id,
    county = county_name,
    zip_code = region_name,
    everything()) |>
  select (-region_type, -state_name, -state, -city, -metro)|>
  pivot_longer(cols = matches("^x"),
               names_to = "date_raw",
               values_to = "zori") |>
  mutate(
    date = date_raw |>
      str_remove("^x") |>
      str_replace_all("_", "-") |>
      as.Date()) |>
  mutate(
    county = county |>
      str_remove(regex("\\s*county\\b", ignore_case = TRUE)) |>
      str_squish()) |>
  select(region_id, county, zip_code, size_rank, date, zori)
```

    ## Rows: 149 Columns: 125
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr   (6): RegionType, StateName, State, City, Metro, CountyName
    ## dbl (119): RegionID, SizeRank, RegionName, 2015-01-31, 2015-02-28, 2015-03-3...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
zori_data
```

    ## # A tibble: 17,284 × 6
    ##    region_id county zip_code size_rank date        zori
    ##        <dbl> <chr>     <dbl>     <dbl> <date>     <dbl>
    ##  1     62080 Queens    11368         4 2015-01-31    NA
    ##  2     62080 Queens    11368         4 2015-02-28    NA
    ##  3     62080 Queens    11368         4 2015-03-31    NA
    ##  4     62080 Queens    11368         4 2015-04-30    NA
    ##  5     62080 Queens    11368         4 2015-05-31    NA
    ##  6     62080 Queens    11368         4 2015-06-30    NA
    ##  7     62080 Queens    11368         4 2015-07-31    NA
    ##  8     62080 Queens    11368         4 2015-08-31    NA
    ##  9     62080 Queens    11368         4 2015-09-30    NA
    ## 10     62080 Queens    11368         4 2015-10-31    NA
    ## # ℹ 17,274 more rows

Read in and tidy zip_code_data

``` r
zip_code_data = 
  read_csv("./zillow_data/Zip Codes.csv") |>
  janitor::clean_names() |>
  select(county, zip_code, neighborhood)
```

    ## Rows: 322 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (4): County, County Code, File Date, Neighborhood
    ## dbl (3): State FIPS, County FIPS, ZipCode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
zip_code_data
```

    ## # A tibble: 322 × 3
    ##    county zip_code neighborhood              
    ##    <chr>     <dbl> <chr>                     
    ##  1 Bronx     10451 High Bridge and Morrisania
    ##  2 Bronx     10452 High Bridge and Morrisania
    ##  3 Bronx     10453 Central Bronx             
    ##  4 Bronx     10454 Hunts Point and Mott Haven
    ##  5 Bronx     10455 Hunts Point and Mott Haven
    ##  6 Bronx     10456 High Bridge and Morrisania
    ##  7 Bronx     10457 Central Bronx             
    ##  8 Bronx     10458 Bronx Park and Fordham    
    ##  9 Bronx     10459 Hunts Point and Mott Haven
    ## 10 Bronx     10460 Central Bronx             
    ## # ℹ 312 more rows

Join two datasets

``` r
zori_final = 
   left_join(zori_data, zip_code_data,
             by = c("zip_code","county"), 
             relationship = "many-to-many") |>
  pivot_wider(
    names_from = "date",
    values_from = "zori") |>
  arrange(zip_code, neighborhood)

zori_final
```

    ## # A tibble: 149 × 121
    ##    region_id county   zip_code size_rank neighborhood  `2015-01-31` `2015-02-28`
    ##        <dbl> <chr>       <dbl>     <dbl> <chr>                <dbl>        <dbl>
    ##  1     61615 New York    10001      4444 Chelsea and …        3855.        3892.
    ##  2     61616 New York    10002       139 Lower East S…        3317.        3297.
    ##  3     61617 New York    10003       710 Lower East S…        3229.        3226.
    ##  4     61618 New York    10004     30490 Lower Manhat…          NA           NA 
    ##  5     61619 New York    10005      9718 Lower Manhat…        3129.        3133.
    ##  6     61620 New York    10006     14713 Lower Manhat…          NA           NA 
    ##  7     61621 New York    10007     10357 Lower Manhat…          NA           NA 
    ##  8     61623 New York    10009       531 Lower East S…        3069.        3082.
    ##  9     61624 New York    10010      2896 Gramercy Par…        3430.        3434.
    ## 10     61625 New York    10011       947 Chelsea and …        3790.        3810.
    ## # ℹ 139 more rows
    ## # ℹ 114 more variables: `2015-03-31` <dbl>, `2015-04-30` <dbl>,
    ## #   `2015-05-31` <dbl>, `2015-06-30` <dbl>, `2015-07-31` <dbl>,
    ## #   `2015-08-31` <dbl>, `2015-09-30` <dbl>, `2015-10-31` <dbl>,
    ## #   `2015-11-30` <dbl>, `2015-12-31` <dbl>, `2016-01-31` <dbl>,
    ## #   `2016-02-29` <dbl>, `2016-03-31` <dbl>, `2016-04-30` <dbl>,
    ## #   `2016-05-31` <dbl>, `2016-06-30` <dbl>, `2016-07-31` <dbl>, …

``` r
n_obs  <- nrow(zori_final)
n_zip  <- dplyr::n_distinct(zori_final$zip_code)
n_hood <- zori_final |> distinct(neighborhood) |> nrow()

zip_missing <- setdiff(zip_code_data$zip_code, zori_data$zip_code)
n_distinct(zip_missing)
```

    ## [1] 171

The final tidy dataset contains 149 observations across 149 unique ZIP
codes and 43 neighborhoods. There are 171 ZIP codes present in the ZIP
lookup but not in the Zillow data. This is likely due to the area has no
housing available. For example, area 10313 is located in Richmond
County, and includes major attractions like Staten Island Mall and
Historic Richmond Town. Zip code 10273 is a “Unique” ZIP code located in
Manhattan primarily encompassing the James A. Farley Building. There is
no housing available in these kinds of areas.

``` r
drops <- zori_final |>
  select(county, zip_code, neighborhood, `2020-01-31`, `2021-01-31`)|>
  filter(!is.na(`2020-01-31`), !is.na(`2021-01-31`)) |>
  mutate(change  = `2021-01-31` - `2020-01-31`) |>  # negative = drop
  arrange(change) |>
  slice_head(n = 10)

drops
```

    ## # A tibble: 10 × 6
    ##    county   zip_code neighborhood               `2020-01-31` `2021-01-31` change
    ##    <chr>       <dbl> <chr>                             <dbl>        <dbl>  <dbl>
    ##  1 New York    10007 Lower Manhattan                   6334.        5422.  -913.
    ##  2 New York    10069 <NA>                              4623.        3875.  -748.
    ##  3 New York    10009 Lower East Side                   3406.        2692.  -714.
    ##  4 New York    10016 Gramercy Park and Murray …        3731.        3019.  -712.
    ##  5 New York    10001 Chelsea and Clinton               4108.        3398.  -710.
    ##  6 New York    10002 Lower East Side                   3645.        2935.  -710.
    ##  7 New York    10004 Lower Manhattan                   3150.        2444.  -706.
    ##  8 New York    10038 Lower Manhattan                   3573.        2876.  -698.
    ##  9 New York    10012 Greenwich Village and Soho        3629.        2942.  -686.
    ## 10 New York    10010 Gramercy Park and Murray …        3697.        3012.  -685.

The table shows the 10 zip codes (along with county and neighborhood)
with the largest drop in price from Jan 2020 to 2021. All 10 are in
Manhattan (New York County), concentrated in Lower Manhattan. This
pattern is consistent with pandemic-time shifts: remote work and online
schooling reduced the need to live close to jobs and campuses, and many
renters left high-cost, dense neighborhoods. With less demand for rental
apartments, rents fell faster in these areas than in the outer boroughs.
